### ISSUE TITLE
Create reporting system to save all error logs from Minecraft in Odoo

### ISSUE THREAD

**Issue by kevinxdev** [gigaclub/gigaclub_odoo#47]
Points to research:
- [x] Find a way to easily catch all errors from a Minecraft Plugin

Let's save the error log, the Plugin name and the datetime. Maybe let's add later better reporting of all player activity to track the behavior of the players that occurs the errors for easier error reproducion.

**Comment by kevinxdev** [comment]
@Feier68 what do you think?

**Comment by kevinxdev** [comment]
@Feier68 lol https://jd.papermc.io/paper/1.19/com/destroystokyo/paper/event/server/ServerExceptionEvent.html

**Comment by Feier68** [comment]
Ich denke das könnte lustig werden.
