### ISSUE TITLE
Bugfixes

### ISSUE THREAD

**Issue by kevinxdev** [gigaclub/gigaclub_odoo#61]
- [x] Here owner_id is missing: https://github.com/gigaclub/gigaclub_odoo/blob/16.0/gigaclub_team/models/gc_team.py#L188
- [x] Something wrong here with the permission check: https://github.com/gigaclub/gigaclub_odoo/blob/16.0/gigaclub_team/models/gc_team.py#L62

**Comment by Feier68** [comment]
builderSystem.getUserWorlds
builderSystem.getTeamWorlds

https://github.com/gigaclub/gigaclub_odoo/blob/16.0/gigaclub_builder_system/models/gc_builder_world.py#L338

abfrage World Owner

**Comment by kevinxdev** [comment]
@Feier68 owner id ist hinzugefügt und Bugs sind beseitigt :)
